### ISSUE TITLE
heap-buffer-overflow in nsvg__curveBounds()

### ISSUE THREAD

**Issue by invd** [memononen/nanosvg#184]
See #178 for context and program setup. Reproducible on newest master commit 07a5e2a33c999c759490c2ca452e18ec24c0bfb3.

```
==13556==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x610000000200 at pc 0x0000005d9720 bp 0x7ffc22f5f7f0 sp 0x7ffc22f5f7e8
READ of size 4 at 0x610000000200 thread T0
    #0 0x5d971f in nsvg__curveBounds /nanosvg/src/./nanosvg.h:578:32
    #1 0x5c40ae in nsvg__addPath /nanosvg/src/./nanosvg.h:1068:3
    #2 0x581526 in nsvg__parsePath /nanosvg/src/./nanosvg.h:2325:4
    #3 0x557774 in nsvg__startElement /nanosvg/src/./nanosvg.h:2702:3
    #4 0x556877 in nsvg__parseElement /nanosvg/src/./nanosvg.h:326:3
    #5 0x552f9a in nsvg__parseXML /nanosvg/src/./nanosvg.h:350:4
    #6 0x556c3d in nsvgParse /nanosvg/src/./nanosvg.h:2903:2
```

Crash input: [oob_read_1.svg.zip](https://github.com/memononen/nanosvg/files/5289181/oob_read_1.svg.zip)

Mentioning @memononen, @oehhar, @fvogelnew1 for visibility.

**Comment by memononen** [comment]
Thanks for reporting, should be fixed now.

**Comment by oehhar** [comment]
Thanks to both of you. Pushed to Tk.

**Comment by invd** [comment]
This looks fixed :+1:
