### ISSUE TITLE
endless loop in nsvg__createGradient()

### ISSUE THREAD

**Issue by invd** [memononen/nanosvg#185]
See #178 for context and program setup. Reproducible on newest master commit 07a5e2a.

Loop:
```C
836		while (ref != NULL) {
(gdb) 
837			if (stops == NULL && ref->stops != NULL) {
(gdb) 
842			i++;
(gdb) 
849			ref = nsvg__findGradientData(p, ref->ref);
(gdb) 
836		while (ref != NULL) {
```

Backtrace:
```C
#0  nsvg__createGradient (p=0x62e000000400, id=0x62e0000005e4 "", localBounds=0x7fffffff9ea0, paintType=0x610000000090 "") at ./nanosvg.h:836
#1  0x00000000005d2f26 in nsvg__addShape (p=0x62e000000400) at ./nanosvg.h:1017
#2  0x000000000058a4ea in nsvg__parseLine (p=0x62e000000400, attr=0x7fffffffbfa0) at ./nanosvg.h:2473
#3  0x0000000000557b65 in nsvg__startElement (ud=0x62e000000400, el=0x7fffffffd123 "line", attr=0x7fffffffbfa0) at ./nanosvg.h:2718
#4  0x0000000000556878 in nsvg__parseElement (s=0x7fffffffd12b "", startelCb=0x556f50 <nsvg__startElement>, endelCb=0x5583f0 <nsvg__endElement>, ud=0x62e000000400) at ./nanosvg.h:326
#5  0x0000000000552f9b in nsvg__parseXML (input=0x7fffffffd100 "", startelCb=0x556f50 <nsvg__startElement>, endelCb=0x5583f0 <nsvg__endElement>, contentCb=0x558980 <nsvg__content>, ud=0x62e000000400) at ./nanosvg.h:350
#6  0x0000000000556c3e in nsvgParse (input=0x7fffffffd100 "", units=0x6110c0 <.str> "px", dpi=96) at ./nanosvg.h:2903
```

Timeout input: [timeout_2.svg.zip](https://github.com/memononen/nanosvg/files/5289192/timeout_2.svg.zip)

Mentioning @memononen, @oehhar, @fvogelnew1 for visibility.

**Comment by memononen** [comment]
Thanks for reporting, should be fixed now.

**Comment by oehhar** [comment]
Thanks to both of you. Pushed to Tk.

**Comment by invd** [comment]
This looks fixed :+1:

**Comment by akien-mga** [comment]
This issue could be closed then.
